-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cache
(
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    expiration bigint NOT NULL,
    CONSTRAINT cache_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.cache_locks
(
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    owner character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expiration bigint NOT NULL,
    CONSTRAINT cache_locks_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.cart_items
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT cart_items_pkey PRIMARY KEY (id),
    CONSTRAINT cart_items_user_id_product_id_unique UNIQUE (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id bigserial NOT NULL,
    parent_id bigint,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_slug_unique UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.colors
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    hex_code character varying(7) COLLATE pg_catalog."default",
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT colors_pkey PRIMARY KEY (id),
    CONSTRAINT colors_slug_unique UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.diameters
(
    id bigserial NOT NULL,
    label character varying(255) COLLATE pg_catalog."default" NOT NULL,
    mm_value numeric(4, 2) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT diameters_pkey PRIMARY KEY (id),
    CONSTRAINT diameters_label_mm_value_unique UNIQUE (label, mm_value)
);

CREATE TABLE IF NOT EXISTS public.failed_jobs
(
    id bigserial NOT NULL,
    uuid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    connection text COLLATE pg_catalog."default" NOT NULL,
    queue text COLLATE pg_catalog."default" NOT NULL,
    payload text COLLATE pg_catalog."default" NOT NULL,
    exception text COLLATE pg_catalog."default" NOT NULL,
    failed_at timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT failed_jobs_pkey PRIMARY KEY (id),
    CONSTRAINT failed_jobs_uuid_unique UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS public.filament_details
(
    id bigserial NOT NULL,
    product_id bigint NOT NULL,
    filament_type_id bigint NOT NULL,
    recommended_nozzle_temp_min smallint,
    recommended_nozzle_temp_max smallint,
    recommended_bed_temp_min smallint,
    recommended_bed_temp_max smallint,
    material_note text COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT filament_details_pkey PRIMARY KEY (id),
    CONSTRAINT filament_details_product_id_unique UNIQUE (product_id)
);

CREATE TABLE IF NOT EXISTS public.filament_types
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT filament_types_pkey PRIMARY KEY (id),
    CONSTRAINT filament_types_slug_unique UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.job_batches
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    total_jobs integer NOT NULL,
    pending_jobs integer NOT NULL,
    failed_jobs integer NOT NULL,
    failed_job_ids text COLLATE pg_catalog."default" NOT NULL,
    options text COLLATE pg_catalog."default",
    cancelled_at integer,
    created_at integer NOT NULL,
    finished_at integer,
    CONSTRAINT job_batches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.jobs
(
    id bigserial NOT NULL,
    queue character varying(255) COLLATE pg_catalog."default" NOT NULL,
    payload text COLLATE pg_catalog."default" NOT NULL,
    attempts smallint NOT NULL,
    reserved_at integer,
    available_at integer NOT NULL,
    created_at integer NOT NULL,
    CONSTRAINT jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.migrations
(
    id serial NOT NULL,
    migration character varying(255) COLLATE pg_catalog."default" NOT NULL,
    batch integer NOT NULL,
    CONSTRAINT migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    id bigserial NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint,
    product_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    product_brand character varying(255) COLLATE pg_catalog."default",
    quantity integer NOT NULL DEFAULT 1,
    unit_price_gross numeric(10, 2) NOT NULL DEFAULT '0'::numeric,
    unit_price_net numeric(10, 2) NOT NULL DEFAULT '0'::numeric,
    line_total numeric(10, 2) NOT NULL DEFAULT '0'::numeric,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id bigserial NOT NULL,
    user_id bigint,
    order_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    customer_first_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_last_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_phone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    billing_country character varying(255) COLLATE pg_catalog."default" NOT NULL,
    billing_street character varying(255) COLLATE pg_catalog."default" NOT NULL,
    billing_house_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    billing_city character varying(255) COLLATE pg_catalog."default" NOT NULL,
    billing_postal_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    delivery_country character varying(255) COLLATE pg_catalog."default" NOT NULL,
    delivery_street character varying(255) COLLATE pg_catalog."default" NOT NULL,
    delivery_house_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    delivery_city character varying(255) COLLATE pg_catalog."default" NOT NULL,
    delivery_postal_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    payment_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    payment_label character varying(255) COLLATE pg_catalog."default" NOT NULL,
    shipping_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    shipping_label character varying(255) COLLATE pg_catalog."default" NOT NULL,
    shipping_eta_label character varying(255) COLLATE pg_catalog."default",
    subtotal numeric(10, 2) NOT NULL DEFAULT '0'::numeric,
    discount_amount numeric(10, 2) NOT NULL DEFAULT '0'::numeric,
    shipping_amount numeric(10, 2) NOT NULL DEFAULT '0'::numeric,
    total_amount numeric(10, 2) NOT NULL DEFAULT '0'::numeric,
    vat_total numeric(10, 2) NOT NULL DEFAULT '0'::numeric,
    placed_at timestamp(0) without time zone,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_order_number_unique UNIQUE (order_number)
);

CREATE TABLE IF NOT EXISTS public.password_reset_tokens
(
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.product_families
(
    id bigserial NOT NULL,
    category_id bigint,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    brand character varying(255) COLLATE pg_catalog."default",
    shared_short_description text COLLATE pg_catalog."default",
    shared_description text COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT product_families_pkey PRIMARY KEY (id),
    CONSTRAINT product_families_slug_unique UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.product_images
(
    id bigserial NOT NULL,
    product_id bigint NOT NULL,
    product_variant_id bigint,
    path character varying(255) COLLATE pg_catalog."default" NOT NULL,
    alt_text character varying(255) COLLATE pg_catalog."default",
    sort_order integer NOT NULL DEFAULT 0,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT product_images_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_variants
(
    id bigserial NOT NULL,
    product_id bigint NOT NULL,
    sku character varying(255) COLLATE pg_catalog."default",
    slug character varying(255) COLLATE pg_catalog."default",
    color_id bigint,
    weight_id bigint,
    diameter_id bigint,
    price_gross numeric(10, 2),
    stock_qty integer NOT NULL DEFAULT 0,
    is_default boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT product_variants_pkey PRIMARY KEY (id),
    CONSTRAINT product_variants_sku_unique UNIQUE (sku),
    CONSTRAINT product_variants_slug_unique UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id bigserial NOT NULL,
    category_id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    brand character varying(255) COLLATE pg_catalog."default" NOT NULL,
    short_description text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    price_gross numeric(10, 2) NOT NULL,
    tax_rate numeric(5, 2) NOT NULL DEFAULT '23'::numeric,
    rating_avg numeric(3, 2),
    rating_count integer NOT NULL DEFAULT 0,
    stock_qty integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    product_family_id bigint,
    color_id bigint,
    weight_id bigint,
    diameter_id bigint,
    variant_label character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_slug_unique UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    payload text COLLATE pg_catalog."default" NOT NULL,
    last_activity integer NOT NULL,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_addresses
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    label character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default" NOT NULL,
    street character varying(255) COLLATE pg_catalog."default" NOT NULL,
    house_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    city character varying(255) COLLATE pg_catalog."default" NOT NULL,
    postal_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_default_billing boolean NOT NULL DEFAULT false,
    is_default_delivery boolean NOT NULL DEFAULT false,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT user_addresses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email_verified_at timestamp(0) without time zone,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    remember_token character varying(100) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    role character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'user'::character varying,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.weights
(
    id bigserial NOT NULL,
    label character varying(255) COLLATE pg_catalog."default" NOT NULL,
    grams integer NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT weights_pkey PRIMARY KEY (id),
    CONSTRAINT weights_label_grams_unique UNIQUE (label, grams)
);

ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT cart_items_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT cart_items_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT categories_parent_id_foreign FOREIGN KEY (parent_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.filament_details
    ADD CONSTRAINT filament_details_filament_type_id_foreign FOREIGN KEY (filament_type_id)
    REFERENCES public.filament_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.filament_details
    ADD CONSTRAINT filament_details_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS filament_details_product_id_unique
    ON public.filament_details(product_id);


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_order_id_foreign FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.product_families
    ADD CONSTRAINT product_families_category_id_foreign FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.product_images
    ADD CONSTRAINT product_images_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.product_images
    ADD CONSTRAINT product_images_product_variant_id_foreign FOREIGN KEY (product_variant_id)
    REFERENCES public.product_variants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.product_variants
    ADD CONSTRAINT product_variants_color_id_foreign FOREIGN KEY (color_id)
    REFERENCES public.colors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.product_variants
    ADD CONSTRAINT product_variants_diameter_id_foreign FOREIGN KEY (diameter_id)
    REFERENCES public.diameters (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.product_variants
    ADD CONSTRAINT product_variants_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.product_variants
    ADD CONSTRAINT product_variants_weight_id_foreign FOREIGN KEY (weight_id)
    REFERENCES public.weights (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_category_id_foreign FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_color_id_foreign FOREIGN KEY (color_id)
    REFERENCES public.colors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_diameter_id_foreign FOREIGN KEY (diameter_id)
    REFERENCES public.diameters (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_product_family_id_foreign FOREIGN KEY (product_family_id)
    REFERENCES public.product_families (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_weight_id_foreign FOREIGN KEY (weight_id)
    REFERENCES public.weights (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.user_addresses
    ADD CONSTRAINT user_addresses_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;