CREATE TABLE Customer (ID SERIAL NOT NULL, "First Name" varchar(32) NOT NULL, "Last Name" varchar(32) NOT NULL, Email varchar(50) NOT NULL UNIQUE, phone_prefix varchar(6) NOT NULL, Phone int4 NOT NULL UNIQUE, Address varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Filaments (ID SERIAL NOT NULL, Brandsid int4 NOT NULL, ShoppingBasketID int4 NOT NULL, ShoppingBasketCustomerID int4 NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Printers (ID SERIAL NOT NULL, Brandsid int4 NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Tools (ID SERIAL NOT NULL, Brandsid int4 NOT NULL, ShoppingBasketID int4 NOT NULL, ShoppingBasketCustomerID int4 NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Brands (id SERIAL NOT NULL, Description varchar(255), PRIMARY KEY (id));
CREATE TABLE CustomerLists (ID int4 NOT NULL, CustomerID int4 NOT NULL, Name varchar(25), PRIMARY KEY (ID, CustomerID));
CREATE TABLE Filaments_CustomerLists (FilamentsID int4 NOT NULL, CustomerListsID int4 NOT NULL, CustomerListsCustomerID int4 NOT NULL, PRIMARY KEY (FilamentsID, CustomerListsID, CustomerListsCustomerID));
CREATE TABLE Printers_CustomerLists (PrintersID int4 NOT NULL, CustomerListsID int4 NOT NULL, CustomerListsCustomerID int4 NOT NULL, PRIMARY KEY (PrintersID, CustomerListsID, CustomerListsCustomerID));
CREATE TABLE Tools_CustomerLists (ToolsID int4 NOT NULL, CustomerListsID int4 NOT NULL, CustomerListsCustomerID int4 NOT NULL, PRIMARY KEY (ToolsID, CustomerListsID, CustomerListsCustomerID));
CREATE TABLE Accesories (ID SERIAL NOT NULL, Name char(100) NOT NULL, Brandsid int4 NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Resins (ID SERIAL NOT NULL, Brandsid int4 NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Orders (ID int4 NOT NULL, CustomerID int4 NOT NULL, is_payed int2 DEFAULT 0 NOT NULL, payment_method varchar(255) NOT NULL CHECK(status IN ('new','paid','cancelled')), PRIMARY KEY (ID, CustomerID));
CREATE TABLE OrderItems (ID int4 NOT NULL, OrdersID int4 NOT NULL, OrdersCustomerID int4 NOT NULL, PrintersID int4, ToolsID int4, AccesoriesID int4, ResinsID int4, FilamentsID int4, Count int4 NOT NULL, PRIMARY KEY (ID, OrdersID));
CREATE TABLE Filaments_Customer (FilamentsID int4 NOT NULL, CustomerID int4 NOT NULL, PRIMARY KEY (FilamentsID, CustomerID));
CREATE TABLE Printers_Customer (PrintersID int4 NOT NULL, CustomerID int4 NOT NULL, PRIMARY KEY (PrintersID, CustomerID));
CREATE TABLE Tools_Customer (ToolsID int4 NOT NULL, CustomerID int4 NOT NULL, PRIMARY KEY (ToolsID, CustomerID));
CREATE TABLE Accesories_Customer (AccesoriesID int4 NOT NULL, CustomerID int4 NOT NULL, PRIMARY KEY (AccesoriesID, CustomerID));
CREATE TABLE Resins_Customer (ResinsID int4 NOT NULL, CustomerID int4 NOT NULL, PRIMARY KEY (ResinsID, CustomerID));
ALTER TABLE Filaments ADD CONSTRAINT FKFilaments226621 FOREIGN KEY (Brandsid) REFERENCES Brands (id);
ALTER TABLE Printers ADD CONSTRAINT FKPrinters401070 FOREIGN KEY (Brandsid) REFERENCES Brands (id);
ALTER TABLE Tools ADD CONSTRAINT FKTools79759 FOREIGN KEY (Brandsid) REFERENCES Brands (id);
ALTER TABLE CustomerLists ADD CONSTRAINT FKCustomerLi433262 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE Filaments_CustomerLists ADD CONSTRAINT FKFilaments_438566 FOREIGN KEY (FilamentsID) REFERENCES Filaments (ID);
ALTER TABLE Filaments_CustomerLists ADD CONSTRAINT FKFilaments_32925 FOREIGN KEY (CustomerListsID, CustomerListsCustomerID) REFERENCES CustomerLists (ID, CustomerID);
ALTER TABLE Printers_CustomerLists ADD CONSTRAINT FKPrinters_C601111 FOREIGN KEY (PrintersID) REFERENCES Printers (ID);
ALTER TABLE Printers_CustomerLists ADD CONSTRAINT FKPrinters_C395056 FOREIGN KEY (CustomerListsID, CustomerListsCustomerID) REFERENCES CustomerLists (ID, CustomerID);
ALTER TABLE Tools_CustomerLists ADD CONSTRAINT FKTools_Cust265787 FOREIGN KEY (ToolsID) REFERENCES Tools (ID);
ALTER TABLE Tools_CustomerLists ADD CONSTRAINT FKTools_Cust282734 FOREIGN KEY (CustomerListsID, CustomerListsCustomerID) REFERENCES CustomerLists (ID, CustomerID);
ALTER TABLE Accesories ADD CONSTRAINT FKAccesories238990 FOREIGN KEY (Brandsid) REFERENCES Brands (id);
ALTER TABLE Resins ADD CONSTRAINT FKResins514230 FOREIGN KEY (Brandsid) REFERENCES Brands (id);
ALTER TABLE Orders ADD CONSTRAINT FKOrders802130 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE Filaments_Customer ADD CONSTRAINT FKFilaments_386293 FOREIGN KEY (FilamentsID) REFERENCES Filaments (ID);
ALTER TABLE Filaments_Customer ADD CONSTRAINT FKFilaments_775992 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE Printers_Customer ADD CONSTRAINT FKPrinters_C229299 FOREIGN KEY (PrintersID) REFERENCES Printers (ID);
ALTER TABLE Printers_Customer ADD CONSTRAINT FKPrinters_C188780 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE Tools_Customer ADD CONSTRAINT FKTools_Cust463549 FOREIGN KEY (ToolsID) REFERENCES Tools (ID);
ALTER TABLE Tools_Customer ADD CONSTRAINT FKTools_Cust930969 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE Accesories_Customer ADD CONSTRAINT FKAccesories587761 FOREIGN KEY (AccesoriesID) REFERENCES Accesories (ID);
ALTER TABLE Accesories_Customer ADD CONSTRAINT FKAccesories24795 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE Resins_Customer ADD CONSTRAINT FKResins_Cus214368 FOREIGN KEY (ResinsID) REFERENCES Resins (ID);
ALTER TABLE Resins_Customer ADD CONSTRAINT FKResins_Cus629391 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
ALTER TABLE OrderItems ADD CONSTRAINT FKOrderItems702970 FOREIGN KEY (OrdersID, OrdersCustomerID) REFERENCES Orders (ID, CustomerID);
ALTER TABLE OrderItems ADD CONSTRAINT FKOrderItems272183 FOREIGN KEY (PrintersID) REFERENCES Printers (ID);
ALTER TABLE OrderItems ADD CONSTRAINT FKOrderItems845281 FOREIGN KEY (ToolsID) REFERENCES Tools (ID);
ALTER TABLE OrderItems ADD CONSTRAINT FKOrderItems925258 FOREIGN KEY (AccesoriesID) REFERENCES Accesories (ID);
ALTER TABLE OrderItems ADD CONSTRAINT FKOrderItems815128 FOREIGN KEY (ResinsID) REFERENCES Resins (ID);
ALTER TABLE OrderItems ADD CONSTRAINT FKOrderItems702401 FOREIGN KEY (FilamentsID) REFERENCES Filaments (ID);
